name: Unit test

on:
 pull_request:
  branches: ['main']

jobs:
 test:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout
     uses: actions/checkout@v3

   - name: Setup .NET
     uses: actions/setup-dotnet@v3
     with:
      dotnet-version: '8.0'
      
   - name: Restore dependencies
     run: dotnet restore ./UnitTestingLab/UnitTestingLab.sln
     
   - name: Build
     run: dotnet build ./UnitTestingLab/UnitTestingLab.sln --no-restore
     
   - name: Run tests
     run: dotnet test ./UnitTestLabTests/UnitTestLabTests.csproj --no-build --verbosity normal
